language: node_js
node_js:
  - '8'
env:
  - TEST_DIR=notification
  - TEST_DIR=extension
before_install:
  - npm i -g npm@^6.4.1
services:
  - docker
script:
  - cd $TEST_DIR
  - npm ci
  - npx lockfile-lint --path package-lock.json --allowed-schemes "https:" "git+https:" --allowed-hosts npm github.com
  - npm run test
  - if [ "$TEST_DIR" = "extension" ]; then npm run cypress; fi
  - cd $TRAVIS_BUILD_DIR

before_deploy:
  - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"

after_deploy:
  - docker logout

deploy:
  - provider: script
    script: bash ./travis-build.sh "$TEST_DIR"
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+
