language: node_js
node_js:
  - '8'
env:
  - TEST_DIR=notification
  - TEST_DIR=extension
before_install:
  - npm i -g npm@^6.4.1
services:
  - docker
script:
  - cd $TEST_DIR
  - npm ci
  - npm run test
  - if [ "$TEST_DIR" = "extension" ]; then npm run cypress; fi

deploy:
  - provider: script
    script: bash ./travis-build.sh
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+