language: node_js
node_js:
  - '8'
env:
  - TEST_DIR=notification
  - TEST_DIR=extension
before_install:
  - npm i -g npm@^6.4.1
before_cache:
  # because travis makes cache before calling "after_success" section we must install gcloud SDK here
  - $CI_SCRIPTS/gcloud-install-sdk.sh || travis_terminate 1
services:
  - docker
script:
  - cd $TEST_DIR
  - npm ci
  - npm run test
  - if [ "$TEST_DIR" = "extension" ]; then npm run cypress; fi
