language: node_js
node_js:
  - '10'
env:
  - TEST_DIR=notification
  - TEST_DIR=extension
before_install:
  - npm i -g npm@^6.9.0
script:
  - cd $TEST_DIR
  - npm ci
  - npm run test
  - if [ "$TEST_DIR" = "extension" ]; then npm run cypress; fi
