version: 1
update_configs:
  - package_manager: javascript
    directory: "/notification"
    update_schedule: "daily"
    automerged_updates:
      - match:
          dependency_name: "*"
  - package_manager: javascript
    directory: "/extension"
    update_schedule: "daily"
    automerged_updates:
      - match:
          dependency_name: "*"