module.exports = {
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',
  CTP_ADYEN_INTEGRATION: 'ctp-adyen-integration',
  CTP_PAYMENT_INTERACTION_CUSTOM_TYPE_KEY: 'ctp-adyen-integration-interaction-payment-type',
  CTP_PAYMENT_CUSTOM_TYPE_KEY: 'ctp-adyen-integration-web-components-payment-type',
  REDIRECT_SHOPPER: 'RedirectShopper',
  CTP_TXN_STATE_INITIAL: 'Initial',
  CTP_TXN_STATE_PENDING: 'Pending',
  CTP_TXN_STATE_SUCCESS: 'Success',
  CTP_TXN_STATE_FAILURE: 'Failure',
  CTP_INTERACTION_TYPE_COMPLETE_PAYMENT: 'completePayment',
  CTP_INTERACTION_TYPE_CANCEL_REFUND: 'cancelOrRefund',
  CTP_INTERACTION_TYPE_GET_PAYMENT_METHODS: 'getPaymentMethods',
  CTP_CUSTOM_FIELD_GET_PAYMENT_METHODS_REQUEST: 'getPaymentMethodsRequest',
  CTP_CUSTOM_FIELD_GET_PAYMENT_METHODS_RESPONSE: 'getPaymentMethodsResponse',
  CTP_INTERACTION_TYPE_GET_ORIGIN_KEYS: 'getOriginKeys',
  CTP_CUSTOM_FIELD_GET_ORIGIN_KEYS_REQUEST: 'getOriginKeysRequest',
  CTP_CUSTOM_FIELD_GET_ORIGIN_KEYS_RESPONSE: 'getOriginKeysResponse',
  CTP_INTERACTION_TYPE_MAKE_PAYMENT: 'makePayment',
  CTP_CUSTOM_FIELD_MAKE_PAYMENT_REQUEST: 'makePaymentRequest',
  CTP_CUSTOM_FIELD_MAKE_PAYMENT_RESPONSE: 'makePaymentResponse',
  CTP_INTERACTION_TYPE_SUBMIT_ADDITIONAL_PAYMENT_DETAILS: 'submitAdditionalPaymentDetails',
  CTP_CUSTOM_FIELD_SUBMIT_ADDITIONAL_PAYMENT_DETAILS_REQUEST: 'submitAdditionalPaymentDetailsRequest',
  CTP_CUSTOM_FIELD_SUBMIT_ADDITIONAL_PAYMENT_DETAILS_RESPONSE: 'submitAdditionalPaymentDetailsResponse',
  PAYMENT_METHOD_TYPE_KLARNA_METHODS: ['klarna', 'klarna_paynow', 'klarna_account']
}
