# This workflow will build docker images and publish to docker hub
# For more information see: https://github.com/marketplace/actions/build-and-push-docker-images

name: CD

on: [push]

jobs:
  docker_notification_module:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: notification
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Image digest extension module
        run: echo ${{ steps.docker_build_extension.outputs.digest }}
      - name: Build and push notification module
        id: docker_build_notification
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: commercetools/commercetools-adyen-integration-notification:latest
      - name: Image digest notification module
        run: echo ${{ steps.docker_build_notification.outputs.digest }}


  docker_extension_module:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: extension
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push extension module
        id: docker_build_extension
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: commercetools/commercetools-adyen-integration-extension:latest
      - name: Image digest extension module
        run: echo ${{ steps.docker_build_extension.outputs.digest }}
