# This workflow will build docker images and publish to docker hub
# For more information see: https://github.com/marketplace/actions/build-and-push-docker-images

name: CD

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push extension module
        id: docker_build_extension
        uses: docker/build-push-action@v5
        with:
          context: ./extension
          file: ./extension/Dockerfile
          push: true
          tags: commercetools/commercetools-adyen-integration-extension:${{ steps.vars.outputs.tag }}
      - name: Build and push notification module
        id: docker_build_notification
        uses: docker/build-push-action@v5
        with:
          context: ./notification
          file: ./notification/Dockerfile
          push: true
          tags: commercetools/commercetools-adyen-integration-notification:${{ steps.vars.outputs.tag }}
