### This workflow now has no secrets and a read-only token
name: Dependabot PR Check

on:
  push:

jobs:
  check_dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - run: echo "PR created by Dependabot"
